version: '3.3'
services:
  mysql:
    image: mysql:8.0
    container_name: meu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbfinanceiro
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
